<h1>EDIT</h1>
<form method="POST" action="index.php?route=user-edit">
    <label for="email">Email</label>
    <input type="email" name="email" id="email"/>
    <label for="username">Username</label>
    <input type="text" name="username" id="username"/>
    <label for="password">Password</label>
    <input type="password" name="password" id="password"/>
    <input type="submit" value="Submit"/>
</form>